config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  get "resume" => "pages#resume", as: :resume
  get "works" => "pages#works"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def resume
  	@resume_details = [
  		{
  			title: "Short Film",
  			items: [
  				"Lost and Found - Box Lunch Stories",
  				"Sad Girl - Directed by Dolan Chorng",
  				"The L Travel - Directed by Nanako Fukui",
  				"Wants of the Flesh - Directed by Atta Liang",
  				"What the Water Gave Him - Directed by Asia Doubikin",
  				"First Date - Directed by Debbie Bian",
  				"Only One Song Left - Directed by Qu Yuchen",
  				"30 Days of Wendy - Directed by James Long",
  				"The Actor - Directed by Ryan Jang",
  				"Golden California - Directed by Morgan Steele"
  			]
  		},
  		{
  			title: "Commercial",
  			items: [
				"SanDisk - Fog City Pictures",
				"Wicue - Red Cube Studio",
				"Grush - Red Cube Studio",
				"Liftee - Glass and Marker",
				"Linco App - Shuntian Jiang"
  			]
  		},
  		{
  			title: "Webseries",
  			items: [
  				"Guilt - Directed by Rosalie Muller-Boiral"
  			]
  		},
  		{  	title: "Theatre",
  			items: [
  				"Cat’s Paw - Dragon Theatre",
				"The Laramie Project - Lohman Theatre",
				"The Revenger’s Tragedy - La Jolla Playhouse",
				"Underground Play Festival’s Walls - UC San Diego",
				"Asian American Theatre Festival - UC San Diego",
				"Monster’s Love - UC San Diego",
				"Knots - UC San Diego"
			]
		}
  	]

  end
  def works
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<header class="row intro">
	<div class="col-sm-12">
		<h1 class="name-header">SARAH LEE <span class="subtitle">SAG eligible actor based in SF.</span></h1> 
	</div>
</header>
<hr>

app/views/layouts/_navbar.html.erb
<nav class="nav nav-inline">
	<%= link_to("Home", root_url, class: "nav-link") %>

	<%= link_to("Resume", resume_path, class: "nav-link") %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActorWebsite</title>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet" type="text/css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container" id="main">
      <%= render "layouts/header" %>
       <%= render "layouts/navbar" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<%= image_tag("photo.png", class: "img-rounded headshot img-fluid") %>

<iframe src="https://player.vimeo.com/video/176806241?autoplay=0&loop=1" width="800" height="450" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

app/views/pages/resume.html.erb
<h1>RESUME</h1>	
<div class="row">
<% @resume_details.each do |resume_details| %>
	<%= render "pages/resume/resume_details", resume_details: resume_details %>
<% end %>


</div>
	<div>
		<h2>Training</h2>		
		American Conservatory Theatre - STC intensive: Lisa Anne Porter, Stephanie Hunt, Mark Jackson, Jessica Berman, Chris Herold, Kimberly Maclean, Letitia Bartlett, Janet Foster
		Meisner Technique Studio: Jim Jarrett, Melissa Thompson
		UC San Diego: Kim Rubinstein, Jim Winker, Charlie Oates, Eva Barnes, Ursula Meyer, Kim Walsh, Rufio Lerma

		<h2>Additional Skills</h2>
		<p>40-hour Trained Domestic Violence Peer Counselor, Fluent Mandarin, Basic Taiwanese, Driver’s License, Yoga, Contemporary Voice, Can Read Sheet Music, Intermediate piano skills, British RP accent, Boston accent</p>

		<h2>Education</h2>
		<p>B.S. General Biology/ Theater minor, Provost’s Honor from UC San Diego</p>
	</div>
</div>

app/views/pages/resume/_resume_details.html.erb
<div class="col-sm-6">
	<h2 class="resume-details"><%= resume_details[:title] %></h2>
	<ul>
		<% resume_details[:items].each do |item| %>
			<li><%= item %></li>
		<% end %>
	</ul>
</div>

app/views/pages/works.html.erb
works.html.erb